:repository-owner: CIRCUITSTATE
:repository-name: CSE_ArduinoRS485
:repository-version: 1.0.13

image::https://socialify.git.ci/CIRCUITSTATE/CSE_ArduinoRS485/image?description=1&font=KoHo&forks=1&issues=1&logo=https%3A%2F%2Fwww.circuitstate.com%2Fwp-content%2Fuploads%2F2024%2F05%2FCIRCUITSTATE-R-Emblem-20052024-2.svg&name=1&pattern=Circuit%20Board&pulls=1&stargazers=1&theme=Auto[CSE_ArduinoRS485]

= {repository-name} =

This Arduino library allows you to send and receive data using the **RS-485** interface standard. Supported by all Arduino-compatible boards such as ESP32, STM32, RP2040, AVR, SAMD, ESP8266, etc. You can use both hardware and software serial ports for communication. This library supports the Maxim Integrated **MAX485** and equivalent external transceivers.

This library is a fork of the https://github.com/arduino-libraries/ArduinoRS485[**ArduinoRS485**] library by Arduino, and is maintained by https://www.circuitstate.com[**CIRCUITSTATE Electronics**].

== Installation ==

This library is available from the official **Arduino Library Manager**. Open the Arduino IDE, search for **{repository-name}** and install the latest version of the library.

Additionally, you can download the latest release package from the GitHub repository and install it manually. To do so, open the Arduino IDE, go to **Sketch > Include Library > Add .ZIP Library...** and select the downloaded file.

Another method is to clone the GitHub repository directly into your **libraries** folder. The development branch will have the latest features, bug fixes and other changes. To do so, navigate to your **libraries** folder (usually located at **Documents/Arduino/libraries** on Windows and **~/Documents/Arduino/libraries** on macOS) and execute the following command:

[source,bash]
----
git clone https://github.com/CIRCUITSTATE/CSE_ArduinoRS485.git
----

The library can also be installed via **PlatformIO**. All officially listed Arduino listed libraries are automatically fetched by PlatformIO. Use the `lib_deps` search option to install the library.

== Examples ==

Three examples are included with this library:

  * **RS485_Sender** - Sends data to a connected receiver.
  * **RS485_Receiver** - Receives data from a connected sender.
  * **RS485_Passthrough** - Sends and receives data between the RS-485 port and the default serial port.

== API Reference ==

You can find the complete API reference for this library at link:docs/API.md[API.md].

== Reference ==

* https://github.com/arduino-libraries/ArduinoRS485[ArduinoRS485 Library by Arduino]
* https://www.arduino.cc/reference/en/libraries/arduinors485/[ArduinoRS485 documentation by Arduino]
* https://www.circuitstate.com/tutorials/what-is-rs-485-how-to-use-max485-with-arduino-for-reliable-long-distance-serial-communication/[RS-485 tutorial by CIRCUITSTATE]
* https://www.circuitstate.com/pinouts/max485-cd4069-rs-485-module-with-auto-data-direction-control-pinout-diagram-and-pin-reference/[MAX485+CD4069 Module Pinout by CIRCUITSTATE]
* https://www.circuitstate.com/tutorials/what-is-modbus-communication-protocol-and-how-to-implement-modbus-rtu-with-arduino/[Modbus RTU tutorial by CIRCUITSTATE]

